---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-watsonx-ai-saas
    kind: solution
    catalog_id: 8bfb1293-8b85-4d3f-a89f-015d0a0719df
    offering_id: e8ad6597-8c1a-466a-8bb7-243a109daaa8
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        validation_type: projects
        project_id: "4b85a2bb-6051-42dd-81ce-b2dd9d3dcaba"
        target_account_name: "watson-da-account"
        destroy_resources_on_failure: false
        destroy_workspace_on_failure: false
        import_only: false
        validation_rg: validation
        scc:
          instance_id: 9312688c-331e-4f62-8553-eafa3aebb978
          region: us-south
