---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-watsonx-ai-saas
    kind: solution
    catalog_id: 8bfb1293-8b85-4d3f-a89f-015d0a0719df
    offering_id: e8ad6597-8c1a-466a-8bb7-243a109daaa8
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
