---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-watsonx-ai-saas
    kind: solution
    catalog_id: 8bfb1293-8b85-4d3f-a89f-015d0a0719df
    offering_id: e8ad6597-8c1a-466a-8bb7-243a109daaa8
    variations:
      - name: standard
        mark_ready: false
        install_type: fullstack
        import_only: false
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
