---
apiVersion: v1
offerings:
  - name: watsonx-ai-SaaS
    kind: solution
    catalog_id: b5c105a0-04ac-4418-ab2a-3696f7f1d96d
    offering_id: 2cc49ba4-5612-4c86-b171-d9b4b34fc52d
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
