---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-watsonx-ai-saas
    kind: solution
    catalog_id: b5c105a0-04ac-4418-ab2a-3696f7f1d96d
    offering_id: 268199b0-46f8-4717-83ce-600e292c5361
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
